<?php
// This file was generated by the Pimcore Bundle Generator.
namespace Idmedia\TranslationstudioBundle;

use Pimcore\Extension\Bundle\AbstractPimcoreBundle;
use Pimcore\Extension\Bundle\PimcoreBundleAdminClassicInterface;
use Pimcore\Extension\Bundle\Traits\BundleAdminClassicTrait;

class IdmediaTranslationstudioBundle extends AbstractPimcoreBundle implements PimcoreBundleAdminClassicInterface
{
    use BundleAdminClassicTrait;

    public function getPath(): string
    {
        return \dirname(__DIR__);
    }

    public function getJsPaths(): array
    {
        return [
            '/bundles/idmediatranslationstudio/js/translationstudio.js'
        ];
    }
    public function getCssPaths(): array
    {
        return [
            '/bundles/idmediatranslationstudio/css/translationstudio.css'
        ];
    }

}